#开发环境配置
server:
  #端口
  port: 8081
spring:
  profiles: test
  #数据源
  datasource:
      url: jdbc:mysql://10.8.5.76:3306/xzcm?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true&useSSL=false
      username: root
      password: root@lishun
      driverClassName: com.mysql.jdbc.Driver
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 100
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
      database: 3
      host: 127.0.0.1
      port: 6379
      password: ok123
      pool:
        #连接池支持的最大连接数
        max-active: 1000
        #连接池中连接用完时,新的请求等待时间,毫秒
        max-wait: 60000
        #连接池中最多可空闲maxIdle个连接
        max-idle: 400
  data:
      mongodb:
          host: 47.107.180.92
          port: 27017
          database: xzcm
          username: admin
          password: ok123

#日志
logging:
  config: classpath:logback-xzcm.xml
  path: /home/logs-test

file:
  path: /home/file/attachment-dev
  url: http://40.107.180.92:8081
  dir:
    upload: ${file.path}/upload
    import: ${file.path}/import
    export: ${file.path}/export
    dirs: ${file.dir.upload},${file.dir.import},${file.dir.export}
  resource.location: file:${file.path}/

gridfs:
  path: 47.107.180.92:8081/api
  localPath: 127.0.0.1:8081/api